package com.twinmind.voicerecorder.data.remote.api

import kotlinx.coroutines.delay
import java.io.File

/**
 * Mock API service for testing without actual API calls
 * Replace with real API implementation when ready
 */
class MockApiService {

    suspend fun transcribeAudio(audioFile: File, chunkNumber: Int): String {
        // Simulate network delay
        delay(2000)

        // Return mock transcript
        return "This is a mock transcript for chunk $chunkNumber. " +
                "In a real implementation, this would be the actual transcribed text from the audio file. " +
                "The audio file is located at ${audioFile.path}."
    }

    suspend fun generateSummary(transcript: String): SummaryResult {
        // Simulate network delay for streaming
        delay(3000)

        return SummaryResult(
            title = "Mock Meeting Summary",
            summary = "This is a mock summary of the meeting. In a real implementation, " +
                    "this would be generated by an LLM based on the full transcript. " +
                    "The summary would highlight the main topics discussed and key takeaways.",
            actionItems = listOf(
                "Review the implementation details",
                "Test the application thoroughly",
                "Prepare documentation for the release",
                "Schedule follow-up meeting"
            ),
            keyPoints = listOf(
                "Discussed project timeline and milestones",
                "Reviewed technical architecture decisions",
                "Identified potential risks and mitigation strategies",
                "Agreed on next steps and responsibilities"
            )
        )
    }

    data class SummaryResult(
        val title: String,
        val summary: String,
        val actionItems: List<String>,
        val keyPoints: List<String>
    )
}
